---

- name: Assessment playbook
  hosts: assessmentserver
  tasks:

    - name: Get Dockerfile and docker-compose.yaml
      get_url:
        url: https://github.com/neamtiu/BoschAssessmentDevOps/archive/refs/heads/main.zip
        dest: /home/assessment/
 
    - name: Create master directory for application
      command: "mkdir /home/assessment/main"
 
    - name: Unzip documents
      unarchive:
        src: /home/assessment/BoschAssessmentDevOps-main.zip
        dest: /home/assessment/main
        remote_src: yes
	
    - name: Remove old app dockerfile
      command: "rm /home/assessment/master/getting-started-master/Dockerfile"
	  
    - name: Move new app dockerfile
      command: "cp /home/assessment/main/BoschAssessmentDevOps-main/assessment/Dockerfile /home/assessment/master/getting-started-master"
	
    - name: Move docker-compose file
      command: "cp /home/assessment/main/BoschAssessmentDevOps-main/assessment/run_app.yaml /home/assessment/master/getting-started-master"
    
    - name: "Start docker-compose files."
      docker_compose:
        project_src: /home/assessment/master/getting-started-master
        files: run_app.yaml