---

- name: Assessment playbook
  hosts: assessmentserver
  tasks:
  
    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Install Python
      yum:
        name: python3
        state: present

    - name: Install Python-pip
      yum:
        name: python3-pip
        state: present

    - name: Install required python packages
      pip:
        name:
          - docker
          - docker-compose

    - name: Get Docker repository
      command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      
    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Start Docker
      service:
       name: docker
       state: started
       enabled: yes
	   
    - name: Get application zip
      get_url:
       url: https://github.com/docker/getting-started/archive/refs/heads/master.zip
       dest: /home/assessment/master.zip

    - name: Create master directory for application
      command: "mkdir /home/assessment/master"
	   
    - name: Unzip application
      unarchive:
        src: /home/assessment/master.zip
        dest: /home/assessment/master
        remote_src: yes

    - name: Get Dockerfile and docker-compose.yaml
      get_url:
        url: https://github.com/neamtiu/BoschAssessmentDevOps/archive/refs/heads/main.zip
        dest: /home/assessment/
 
    - name: Create master directory for application
      command: "mkdir /home/assessment/main"
 
    - name: Unzip documents
      unarchive:
        src: /home/assessment/BoschAssessmentDevOps-main.zip
        dest: /home/assessment/main
        remote_src: yes

    - name: Remove old app dockerfile
      command: "rm /home/assessment/master/getting-started-master/Dockerfile"

    - name: Move new app dockerfile
      command: "cp /home/assessment/main/BoschAssessmentDevOps-main/assessment/Dockerfile /home/assessment/master/getting-started-master"

    - name: Move docker-compose file
      command: "cp /home/assessment/main/BoschAssessmentDevOps-main/assessment/run_app.yaml /home/assessment/master/getting-started-master"

    - name: Build app docker image
      docker_image:
        name: todoapp:v1.0
        build:
          path: /home/assessment/master/getting-started-master/
        source: build
        state: present

    - name: Pull mysql docker image
      docker_image:
        name: mysql
        tag: 5.7
        source: pull

    - name: Run app using docker-compose
      docker_compose:
        project_src: /home/assessment/master/getting-started-master
        files: run_app.yaml