---

- name: Assessment playbook
  hosts: assessmentserver
  tasks:
  
    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present
    
    - name: Install Python
      yum:
        name: python3
        state: present

    - name: Install Python-pip
      yum:
        name: python3-pip
        state: present

    - name: Get Docker repository
      yum_repository:
        name: Docker
        description: Docker repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      package:
        name: docker-ce-18.06.3.ce-3.e17.x86_64
        state: present
    
    - name: Start Docker
      service:
       name: docker
       state: started
       enabled: yes
